# Generated by Django 6.0.1 on 2026-01-17
# Migration to add buyer_cleared_at and seller_cleared_at fields
# Uses TRY/EXCEPT to handle existing columns gracefully

from django.db import migrations


def add_cleared_at_fields(apps, schema_editor):
    """Add cleared_at fields if they don't exist"""
    with schema_editor.connection.cursor() as cursor:
        # Try to add buyer_cleared_at
        try:
            cursor.execute("""
                ALTER TABLE chat_conversation 
                ADD COLUMN buyer_cleared_at TIMESTAMP WITH TIME ZONE NULL
            """)
        except Exception:
            # Column already exists, skip
            pass
        
        # Try to add seller_cleared_at
        try:
            cursor.execute("""
                ALTER TABLE chat_conversation 
                ADD COLUMN seller_cleared_at TIMESTAMP WITH TIME ZONE NULL
            """)
        except Exception:
            # Column already exists, skip
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_cleared_at_fields, migrations.RunPython.noop),
    ]
