# Generated by Django 6.0.1 on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_cleared_at',
            field=models.DateTimeField(blank=True, help_text='When buyer cleared chat history', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_cleared_at',
            field=models.DateTimeField(blank=True, help_text='When seller cleared chat history', null=True),
        ),
    ]
