# Generated by Django 6.0.1 on 2026-01-17
# Safe migration that checks for existing columns

from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s
        """, [table_name, column_name])
        return cursor.fetchone() is not None


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        # Only add buyer_cleared_at if it doesn't exist
        migrations.RunPython(
            lambda apps, schema_editor: None if check_column_exists('chat_conversation', 'buyer_cleared_at') else 
            schema_editor.execute('ALTER TABLE chat_conversation ADD COLUMN buyer_cleared_at TIMESTAMP WITH TIME ZONE NULL'),
            migrations.RunPython.noop
        ),
        # Only add seller_cleared_at if it doesn't exist
        migrations.RunPython(
            lambda apps, schema_editor: None if check_column_exists('chat_conversation', 'seller_cleared_at') else 
            schema_editor.execute('ALTER TABLE chat_conversation ADD COLUMN seller_cleared_at TIMESTAMP WITH TIME ZONE NULL'),
            migrations.RunPython.noop
        ),
    ]
