# Generated by Django 6.0.1 on 2026-01-17
# GHOST FIX: Empty operations to bypass duplicate column error
# The columns already exist in production database
# This migration will be marked as applied without doing anything

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_buyer_cleared_at_and_more'),
    ]

    # TEMPORARILY EMPTY - columns already exist in database
    # This allows Django to mark the migration as applied
    operations = [
        # Empty - Ghost Fix
    ]
