# Generated by Django 6.0.1 on 2026-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_created_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='pendingregistration',
            index=models.Index(fields=['is_verified', 'is_used'], name='users_pendi_is_veri_ea3a63_idx'),
        ),
    ]
