# Generated by Django 6.0.1 on 2026-01-14 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_deactivated_at_listing_deactivation_reason_and_more'),
        ('users', '0002_user_email_otp_user_email_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('otp_hash', models.CharField(max_length=128)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('last_resend_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
                'indexes': [models.Index(fields=['email'], name='users_pendi_email_2ec85b_idx'), models.Index(fields=['otp_created_at'], name='users_pendi_otp_cre_eda784_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete_listing', 'Deleted Listing'), ('deactivate_listing', 'Deactivated Listing'), ('activate_listing', 'Activated Listing'), ('suspend_user', 'Suspended User'), ('activate_user', 'Activated User'), ('resolve_report', 'Resolved Report'), ('dismiss_report', 'Dismissed Report')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
                ('target_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listingreport')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='users_admin_admin_i_dc56bf_idx'), models.Index(fields=['-created_at'], name='users_admin_created_3c71b7_idx')],
            },
        ),
    ]
