# Generated by Django 6.0.1 on 2026-01-17 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendingregistration_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrustScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('trust_level', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_trust_user_id_207af3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=50, help_text='Overall trust score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('account_age_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('verification_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('listing_quality_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('transaction_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('behavior_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('trust_level', models.CharField(choices=[('new', 'New User'), ('basic', 'Basic'), ('trusted', 'Trusted'), ('verified', 'Verified'), ('elite', 'Elite')], default='new', max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('total_listings', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('sold_listings', models.IntegerField(default=0)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_conversations', models.IntegerField(default=0)),
                ('reports_received', models.IntegerField(default=0)),
                ('spam_violations', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['-score'], name='users_usert_score_f94afa_idx'), models.Index(fields=['trust_level'], name='users_usert_trust_l_68c407_idx')],
            },
        ),
    ]
